### ISSUE TITLE
On Linux, up/down arrows in main menu do not work

### ISSUE THREAD

**Issue by phoe** [gwathlobal/CotD#3]
SBCL 1.3.14.debian - the arrows don't move the cursor in the main menu,

**Comment by gwathlobal** [comment]
@phoe 
Hi, I installed Debian x64 into a VirtualBox and I can not reproduce the bug.
Could you please tell me in detail the steps to do so and upload the bugged executable you created.

**Comment by gwathlobal** [comment]
Ok, thanks to these guys I might have found the source of the problem and fixed it. 
Just in case, try to press Num Lock, this should unblock the arrow keys.
Will be available in the next release.
