### ISSUE TITLE
Game Crashes on Evolution of Increase Acid Strength

### ISSUE THREAD

**Issue by JGelfand** [gwathlobal/CotD#5]
Playing on the 64 bit windows release, the evolution starts as normal but the game crashes after the countdown should hit 0.

**Comment by gwathlobal** [comment]
Found the bug, will be fixed in the next release.

**Comment by gwathlobal** [comment]
Fixed in [v1.2.6](https://github.com/gwathlobal/CotD/releases/tag/v1.2.6)
