### ISSUE TITLE
Weird crash in campaing mode

### ISSUE THREAD

**Issue by Sofistico** [gwathlobal/CotD#7]
When i tried to play Celestial Purge, it returned this error:
![image](https://user-images.githubusercontent.com/59299346/90088760-17f1a780-dcf6-11ea-8b0f-3640c51c22c9.png)

I will post here the log as well:
[log.txt](https://github.com/gwathlobal/CotD/files/5066886/log.txt)

**Comment by gwathlobal** [comment]
Ok, thanks for the info. I managed to pinpoint the problem, the fix is in master and will be available in the next release.
